import * as model from './model';

export const ageRanges = [
  { id: 15.5, name: "14-17" },
  { id: 20.5, name: "18-23" },
  { id: 31.5, name: "24-39" },
  { id: 44.5, name: "40-49" },
  { id: 54.5, name: "50-59" },
  { id: 64.5, name: "60-69" },
  { id: 74.5, name: "70-79" },
  { id: 84.5, name: "80-89" },
];

export const workoutRoutines : model.WorkoutRoutine[] = [
  {
    name: "Bench Press",
    slug: "bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Squat",
    slug: "squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: ["Back Squat"],
  },
  {
    name: "Deadlift",
    slug: "deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Shoulder Press",
    slug: "shoulder-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: ["Overhead Press", "Standing Military Press"],
  },
  {
    name: "Barbell Curl",
    slug: "barbell-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: ["Bicep Curl", "Curls"],
  },
  {
    name: "Hip Thrust",
    slug: "hip-thrust",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: ["Barbell Hip Thrust"],
  },
  {
    name: "Bent Over Row",
    slug: "bent-over-row",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: ["Barbell Row"],
  },
  {
    name: "Sumo Deadlift",
    slug: "sumo-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Front Squat",
    slug: "front-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: ["Barbell Front Squat"],
  },
  {
    name: "Incline Bench Press",
    slug: "incline-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: ["Incline Press", "Barbell Incline Press"],
  },
  {
    name: "Hex Bar Deadlift",
    slug: "hex-bar-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [
      "Trap Bar Deadlift",
      "Trapbar Deadlift",
      "Hex Bar Squat",
      "Hex Squat",
      "Hex Deadlift",
    ],
  },
  {
    name: "Romanian Deadlift",
    slug: "romanian-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Military Press",
    slug: "military-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: ["Seated Military Press"],
  },
  {
    name: "Seated Shoulder Press",
    slug: "seated-shoulder-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: ["Seated Barbell Shoulder Press", "Seated Barbell Overhead Press"],
  },
  {
    name: "EZ Bar Curl",
    slug: "ez-bar-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Lying Tricep Extension",
    slug: "lying-tricep-extension",
    bodyPart: "Triceps",
    type: "barbell",
    category: "Barbell",
    aliases: ["Skull Crusher", "Skullcrusher"],
  },
  {
    name: "Preacher Curl",
    slug: "preacher-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: ["Barbell Preacher Curl"],
  },
  {
    name: "Rack Pull",
    slug: "rack-pull",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Close Grip Bench Press",
    slug: "close-grip-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Pendlay Row",
    slug: "pendlay-row",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Box Squat",
    slug: "box-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Bulgarian Split Squat",
    slug: "bulgarian-split-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Decline Bench Press",
    slug: "decline-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: ["Decline Press"],
  },
  {
    name: "Barbell Shrug",
    slug: "barbell-shrug",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Paused Bench Press",
    slug: "paused-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: ["Pause Press"],
  },
  {
    name: "Bodyweight Calf Raise",
    slug: "bodyweight-calf-raise",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Standing Calf Raise"],
  },
  {
    name: "Stiff Leg Deadlift",
    slug: "stiff-leg-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: ["Stiff Legged Deadlift", "Straight Legged Deadlift"],
  },
  {
    name: "Floor Press",
    slug: "floor-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: ["Barbell Floor Press"],
  },
  {
    name: "Sumo Squat",
    slug: "sumo-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Zercher Deadlift",
    slug: "zercher-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Tricep Extension",
    slug: "tricep-extension",
    bodyPart: "Triceps",
    type: "barbell",
    category: "Barbell",
    aliases: ["French Press"],
  },
  {
    name: "Barbell Calf Raise",
    slug: "barbell-calf-raise",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Pin Squat",
    slug: "pin-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Reverse Lunge",
    slug: "barbell-reverse-lunge",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "T-Bar Row",
    slug: "t-bar-row",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Lunge",
    slug: "barbell-lunge",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Belt Squat",
    slug: "belt-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Zercher Squat",
    slug: "zercher-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Glute Bridge",
    slug: "barbell-glute-bridge",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Good Morning",
    slug: "good-morning",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Strict Curl",
    slug: "strict-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Z Press",
    slug: "z-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Wrist Curl",
    slug: "wrist-curl",
    bodyPart: "Forearms",
    type: "barbell",
    category: "Barbell",
    aliases: ["Forearm Curl", "Wrist Curl Palm Up"],
  },
  {
    name: "Pause Deadlift",
    slug: "pause-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Deficit Deadlift",
    slug: "deficit-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Upright Row",
    slug: "upright-row",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Safety Bar Squat",
    slug: "safety-bar-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [
      "Ssb Squat",
      "Safety Squat Bar",
      "Safety Squat",
      "Safety Squat Bar Squat",
    ],
  },
  {
    name: "Neck Extension",
    slug: "neck-extension",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Neck Curl",
    slug: "neck-curl",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: ["Neck Flexion"],
  },
  {
    name: "Split Squat",
    slug: "split-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Paused Squat",
    slug: "paused-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Walking Lunge",
    slug: "walking-lunge",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Pause Squat",
    slug: "pause-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Pullover",
    slug: "barbell-pullover",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Hack Squat",
    slug: "barbell-hack-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Behind The Neck Press",
    slug: "behind-the-neck-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: ["Back Press", "Press Behind Neck"],
  },
  {
    name: "Snatch Grip Deadlift",
    slug: "snatch-grip-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Log Press",
    slug: "log-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Reverse Grip Bench Press",
    slug: "reverse-grip-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Donkey Calf Raise",
    slug: "donkey-calf-raise",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Wide Grip Bench Press",
    slug: "wide-grip-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Snatch Deadlift",
    slug: "snatch-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Single Leg Romanian Deadlift",
    slug: "single-leg-romanian-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Yates Row",
    slug: "yates-row",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: ["Reverse Grip Bent Over Row"],
  },
  {
    name: "Landmine Press",
    slug: "landmine-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: ["Landmine Chest Press", "Standing Landmine Press"],
  },
  {
    name: "Jefferson Deadlift",
    slug: "jefferson-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Reverse Barbell Curl",
    slug: "reverse-barbell-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Reverse Wrist Curl",
    slug: "reverse-wrist-curl",
    bodyPart: "Forearms",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Single Arm Landmine Press",
    slug: "single-arm-landmine-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Behind The Back Barbell Shrug",
    slug: "behind-the-back-barbell-shrug",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Viking Press",
    slug: "viking-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Spider Curl",
    slug: "spider-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Front Raise",
    slug: "barbell-front-raise",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Single Leg Deadlift",
    slug: "single-leg-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Reverse Curl",
    slug: "reverse-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Landmine Squat",
    slug: "landmine-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Behind The Back Deadlift",
    slug: "behind-the-back-deadlift",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Pin Bench Press",
    slug: "pin-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Close Grip Incline Bench Press",
    slug: "close-grip-incline-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Half Squat",
    slug: "half-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Spoto Press",
    slug: "spoto-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Barbell Power Shrug",
    slug: "barbell-power-shrug",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Shoulder Pin Press",
    slug: "shoulder-pin-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Bench Pin Press",
    slug: "bench-pin-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Barbell",
    aliases: ["Barbell Pin Press"],
  },
  {
    name: "Bench Pull",
    slug: "bench-pull",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: ["Seal Row"],
  },
  {
    name: "Hex Bar Shrug",
    slug: "hex-bar-shrug",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Meadows Row",
    slug: "meadows-row",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Machine Shrug",
    slug: "machine-shrug",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Jefferson Squat",
    slug: "jefferson-squat",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Bent Arm Barbell Pullover",
    slug: "bent-arm-barbell-pullover",
    bodyPart: "Back",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Cheat Curl",
    slug: "cheat-curl",
    bodyPart: "Biceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "JM Press",
    slug: "jm-press",
    bodyPart: "Triceps",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Wall Ball",
    slug: "wall-ball",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Barbell",
    aliases: [],
  },
  {
    name: "Ab Wheel Rollout",
    slug: "ab-wheel-rollout",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Barbell",
    aliases: ["Ab Roller"],
  },
  {
    name: "Pull Ups",
    slug: "pull-ups",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Pullup", "Assisted Pull Up Machine"],
  },
  {
    name: "Push Ups",
    slug: "push-ups",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Press Up"],
  },
  {
    name: "Dips",
    slug: "dips",
    bodyPart: "Triceps",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Tricep Dips", "Chest Dip"],
  },
  {
    name: "Chin Ups",
    slug: "chin-ups",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Sit Ups",
    slug: "sit-ups",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Bodyweight Squat",
    slug: "bodyweight-squat",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Decline Crunch",
    slug: "decline-crunch",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Muscle Ups",
    slug: "muscle-ups",
    bodyPart: "Whole Body",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Glute Bridge",
    slug: "glute-bridge",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Bridging"],
  },
  {
    name: "Ring Dips",
    slug: "ring-dips",
    bodyPart: "Triceps",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Handstand Push Ups",
    slug: "handstand-push-ups",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Decline Push Up",
    slug: "decline-push-up",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Decline Press Up"],
  },
  {
    name: "One Arm Push Ups",
    slug: "one-arm-push-ups",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Crunches",
    slug: "crunches",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Ab Crunch"],
  },
  {
    name: "Diamond Push Ups",
    slug: "diamond-push-ups",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Diamond Pushups"],
  },
  {
    name: "Back Extension",
    slug: "back-extension",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Hyper Extension", "Hyperextension"],
  },
  {
    name: "Neutral Grip Pull Ups",
    slug: "neutral-grip-pull-ups",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Lying Leg Raise",
    slug: "lying-leg-raise",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Lunge",
    slug: "lunge",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Pistol Squat",
    slug: "pistol-squat",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Burpees",
    slug: "burpees",
    bodyPart: "Whole Body",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Single Leg Squat",
    slug: "single-leg-squat",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Hanging Leg Raise",
    slug: "hanging-leg-raise",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Squat Jumps",
    slug: "squat-jumps",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Jump Squat"],
  },
  {
    name: "Nordic Hamstring Curl",
    slug: "nordic-hamstring-curl",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Inverted Row",
    slug: "inverted-row",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Supine Row", "Australian Pull Ups"],
  },
  {
    name: "Ring Muscle Ups",
    slug: "ring-muscle-ups",
    bodyPart: "Whole Body",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Russian Twist",
    slug: "russian-twist",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Hanging Knee Raise",
    slug: "hanging-knee-raise",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "One Arm Pull Ups",
    slug: "one-arm-pull-ups",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Incline Push Up",
    slug: "incline-push-up",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Incline Press Up"],
  },
  {
    name: "Clap Pull Up",
    slug: "clap-pull-up",
    bodyPart: "Whole Body",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Reverse Lunge",
    slug: "reverse-lunge",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Pike Push Up",
    slug: "pike-push-up",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Floor Hip Extension",
    slug: "floor-hip-extension",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Floor Hip Abduction",
    slug: "floor-hip-abduction",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Sissy Squat",
    slug: "sissy-squat",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Close Grip Push Up",
    slug: "close-grip-push-up",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Glute Ham Raise",
    slug: "glute-ham-raise",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Scissor Kicks",
    slug: "scissor-kicks",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Superman",
    slug: "superman",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Incline Bench Sit Up",
    slug: "incline-bench-sit-up",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Bicycle Crunch",
    slug: "bicycle-crunch",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Reverse Hyperextension",
    slug: "reverse-hyperextension",
    bodyPart: "Back",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Glute Kickback",
    slug: "glute-kickback",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Archer Push Ups",
    slug: "archer-push-ups",
    bodyPart: "Chest",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Star Jump",
    slug: "star-jump",
    bodyPart: "Whole Body",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Squat Thrust",
    slug: "squat-thrust",
    bodyPart: "Whole Body",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Side Lunge",
    slug: "side-lunge",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Side Crunch",
    slug: "side-crunch",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: ["Oblique Crunch"],
  },
  {
    name: "Roman Chair Side Bend",
    slug: "roman-chair-side-bend",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Mountain Climbers",
    slug: "mountain-climbers",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Leg Lift",
    slug: "leg-lift",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Jumping Jack",
    slug: "jumping-jack",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Hip Extension",
    slug: "hip-extension",
    bodyPart: "Legs",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Flutter Kicks",
    slug: "flutter-kicks",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Reverse Crunches",
    slug: "reverse-crunches",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Bench Dips",
    slug: "bench-dips",
    bodyPart: "Triceps",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Toes To Bar",
    slug: "toes-to-bar",
    bodyPart: "Core",
    type: "bodyweight",
    category: "Bodyweight",
    aliases: [],
  },
  {
    name: "Power Clean",
    slug: "power-clean",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: ["Powerclean"],
  },
  {
    name: "Clean and Jerk",
    slug: "clean-and-jerk",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Push Press",
    slug: "push-press",
    bodyPart: "Shoulders",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Snatch",
    slug: "snatch",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Clean",
    slug: "clean",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: ["Squat Clean"],
  },
  {
    name: "Dumbbell Snatch",
    slug: "dumbbell-snatch",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Olympic",
    aliases: ["One Arm Dumbbell Snatch"],
  },
  {
    name: "Clean and Press",
    slug: "clean-and-press",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Hang Clean",
    slug: "hang-clean",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Dumbbell Clean and Press",
    slug: "dumbbell-clean-and-press",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Thruster",
    slug: "thruster",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Dumbbell Push Press",
    slug: "dumbbell-push-press",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Power Snatch",
    slug: "power-snatch",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Overhead Squat",
    slug: "overhead-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Push Jerk",
    slug: "push-jerk",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Dumbbell Thruster",
    slug: "dumbbell-thruster",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Clean Pull",
    slug: "clean-pull",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Split Jerk",
    slug: "split-jerk",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Hang Snatch",
    slug: "hang-snatch",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Dumbbell Hang Clean",
    slug: "dumbbell-hang-clean",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Dumbbell High Pull",
    slug: "dumbbell-high-pull",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Muscle Snatch",
    slug: "muscle-snatch",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Hang Power Clean",
    slug: "hang-power-clean",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Snatch Pull",
    slug: "snatch-pull",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Clean High Pull",
    slug: "clean-high-pull",
    bodyPart: "Whole Body",
    type: "barbell",
    category: "Olympic",
    aliases: [],
  },
  {
    name: "Dumbbell Shoulder Press",
    slug: "dumbbell-shoulder-press",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Press"],
  },
  {
    name: "Dumbbell Bench Press",
    slug: "dumbbell-bench-press",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Chest Press"],
  },
  {
    name: "Dumbbell Curl",
    slug: "dumbbell-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Incline Dumbbell Bench Press",
    slug: "incline-dumbbell-bench-press",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Incline Dumbbell Press"],
  },
  {
    name: "Dumbbell Row",
    slug: "dumbbell-row",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Bent Over Row", "One Arm Dumbbell Row", "One Arm Row"],
  },
  {
    name: "Dumbbell Lateral Raise",
    slug: "dumbbell-lateral-raise",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Hammer Curl",
    slug: "hammer-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Hammer Curl", "Hammer Curls"],
  },
  {
    name: "Dumbbell Fly",
    slug: "dumbbell-fly",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Chest Fly"],
  },
  {
    name: "Dumbbell Bulgarian Split Squat",
    slug: "dumbbell-bulgarian-split-squat",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Lunge",
    slug: "dumbbell-lunge",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Lunges"],
  },
  {
    name: "Dumbbell Squat",
    slug: "dumbbell-squat",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Goblet Squat",
    slug: "goblet-squat",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Tricep Extension",
    slug: "dumbbell-tricep-extension",
    bodyPart: "Triceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Split Squat",
    slug: "dumbbell-split-squat",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Tricep Kickback",
    slug: "dumbbell-tricep-kickback",
    bodyPart: "Triceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Kickback"],
  },
  {
    name: "Incline Dumbbell Curl",
    slug: "incline-dumbbell-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Incline Curl", "Incline Curl With Dumbbell"],
  },
  {
    name: "Dumbbell Wrist Curl",
    slug: "dumbbell-wrist-curl",
    bodyPart: "Forearms",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    slug: "seated-dumbbell-shoulder-press",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Seated Dumbbell Press"],
  },
  {
    name: "Dumbbell Romanian Deadlift",
    slug: "dumbbell-romanian-deadlift",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Shrug",
    slug: "dumbbell-shrug",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Shoulder Shrug"],
  },
  {
    name: "Bent Over Dumbbell Row",
    slug: "bent-over-dumbbell-row",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Concentration Curl",
    slug: "dumbbell-concentration-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Incline Dumbbell Fly",
    slug: "incline-dumbbell-fly",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Pullover",
    slug: "dumbbell-pullover",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Straight Arm Pullover"],
  },
  {
    name: "Arnold Press",
    slug: "arnold-press",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Front Raise",
    slug: "dumbbell-front-raise",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Seated Dumbbell Curl",
    slug: "seated-dumbbell-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Z Press",
    slug: "dumbbell-z-press",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Deadlift",
    slug: "dumbbell-deadlift",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Lying Dumbbell Tricep Extension",
    slug: "lying-dumbbell-tricep-extension",
    bodyPart: "Triceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Decline Dumbbell Fly",
    slug: "decline-dumbbell-fly",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Chest Supported Dumbbell Row",
    slug: "chest-supported-dumbbell-row",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Chest Supported Row", "Incline Dumbbell Row"],
  },
  {
    name: "Dumbbell Reverse Fly",
    slug: "dumbbell-reverse-fly",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [
      "Rear Delt Fly",
      "Bent Over Lateral Raise",
      "Bent Over Raise",
      "Bent Over Lateral Raise With Dumbbell",
    ],
  },
  {
    name: "Dumbbell Face Pull",
    slug: "dumbbell-face-pull",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Tate Press",
    slug: "tate-press",
    bodyPart: "Triceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Zottman Curl",
    slug: "zottman-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Reverse Wrist Curl",
    slug: "dumbbell-reverse-wrist-curl",
    bodyPart: "Forearms",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Floor Press",
    slug: "dumbbell-floor-press",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Side Bend",
    slug: "dumbbell-side-bend",
    bodyPart: "Core",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Close Grip Dumbbell Bench Press",
    slug: "close-grip-dumbbell-bench-press",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Close Grip Dumbbell Press"],
  },
  {
    name: "Dumbbell Preacher Curl",
    slug: "dumbbell-preacher-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["One Arm Dumbbell Preacher Curl"],
  },
  {
    name: "Single Leg Dumbbell Deadlift",
    slug: "single-leg-dumbbell-deadlift",
    bodyPart: "Whole Body",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Reverse Curl",
    slug: "dumbbell-reverse-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Seated Dumbbell Tricep Extension",
    slug: "seated-dumbbell-tricep-extension",
    bodyPart: "Triceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Calf Raise",
    slug: "dumbbell-calf-raise",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Front Squat",
    slug: "dumbbell-front-squat",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Incline Y Raise",
    slug: "dumbbell-incline-y-raise",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Walking Calf Raise",
    slug: "dumbbell-walking-calf-raise",
    bodyPart: "Legs",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Incline Hammer Curl",
    slug: "incline-hammer-curl",
    bodyPart: "Biceps",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Renegade Row",
    slug: "renegade-row",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Decline Dumbbell Bench Press",
    slug: "decline-dumbbell-bench-press",
    bodyPart: "Chest",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Decline Dumbbell Press"],
  },
  {
    name: "Dumbbell External Rotation",
    slug: "dumbbell-external-rotation",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Upright Row",
    slug: "dumbbell-upright-row",
    bodyPart: "Shoulders",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: [],
  },
  {
    name: "Dumbbell Bench Pull",
    slug: "dumbbell-bench-pull",
    bodyPart: "Back",
    type: "dumbbell",
    category: "Dumbbell",
    aliases: ["Dumbbell Seal Row"],
  },
  {
    name: "Sled Leg Press",
    slug: "sled-leg-press",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Leg Extension",
    slug: "leg-extension",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Horizontal Leg Press",
    slug: "horizontal-leg-press",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: ["Seated Leg Press"],
  },
  {
    name: "Hack Squat",
    slug: "hack-squat",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Seated Leg Curl",
    slug: "seated-leg-curl",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: ["Hamstring Curl"],
  },
  {
    name: "Chest Press",
    slug: "chest-press",
    bodyPart: "Chest",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Machine Shoulder Press",
    slug: "machine-shoulder-press",
    bodyPart: "Shoulders",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Machine Chest Fly",
    slug: "machine-chest-fly",
    bodyPart: "Chest",
    type: "machine",
    category: "Machine",
    aliases: [
      "Pec Deck Fly",
      "Butterfly",
      "Machine Fly",
      "Fly Machine",
      "Pec Deck",
      "Pec Fly",
    ],
  },
  {
    name: "Lying Leg Curl",
    slug: "lying-leg-curl",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Machine Row",
    slug: "machine-row",
    bodyPart: "Back",
    type: "machine",
    category: "Machine",
    aliases: ["Hammer Strength Row"],
  },
  {
    name: "Machine Calf Raise",
    slug: "machine-calf-raise",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Seated Calf Raise",
    slug: "seated-calf-raise",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Vertical Leg Press",
    slug: "vertical-leg-press",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Smith Machine Squat",
    slug: "smith-machine-squat",
    bodyPart: "Legs",
    type: "barbell",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Smith Machine Bench Press",
    slug: "smith-machine-bench-press",
    bodyPart: "Chest",
    type: "barbell",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Close Grip Lat Pulldown",
    slug: "close-grip-lat-pulldown",
    bodyPart: "Back",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Hip Adduction",
    slug: "hip-adduction",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Machine Bicep Curl",
    slug: "machine-bicep-curl",
    bodyPart: "Biceps",
    type: "machine",
    category: "Machine",
    aliases: ["Machine Curl"],
  },
  {
    name: "Machine Lateral Raise",
    slug: "machine-lateral-raise",
    bodyPart: "Shoulders",
    type: "machine",
    category: "Machine",
    aliases: ["Nautilus Lateral Raise"],
  },
  {
    name: "Hip Abduction",
    slug: "hip-abduction",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Machine Reverse Fly",
    slug: "machine-reverse-fly",
    bodyPart: "Back",
    type: "machine",
    category: "Machine",
    aliases: [
      "Machine Rear Deltoid Fly",
      "Rear Delt Machine",
      "Reverse Pec Deck Fly",
    ],
  },
  {
    name: "Machine Seated Crunch",
    slug: "machine-seated-crunch",
    bodyPart: "Core",
    type: "machine",
    category: "Machine",
    aliases: ["Machine Crunches", "Abdominal Crunch"],
  },
  {
    name: "Seated Dip Machine",
    slug: "seated-dip-machine",
    bodyPart: "Triceps",
    type: "machine",
    category: "Machine",
    aliases: ["Machine Dip"],
  },
  {
    name: "Single Leg Press",
    slug: "single-leg-press",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: ["Single Leg Leg Press"],
  },
  {
    name: "Machine Tricep Press",
    slug: "machine-tricep-press",
    bodyPart: "Triceps",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Smith Machine Shrug",
    slug: "smith-machine-shrug",
    bodyPart: "Back",
    type: "barbell",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Machine Back Extension",
    slug: "machine-back-extension",
    bodyPart: "Back",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Sled Press Calf Raise",
    slug: "sled-press-calf-raise",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: ["Leg Press Calf Raise"],
  },
  {
    name: "Machine Tricep Extension",
    slug: "machine-tricep-extension",
    bodyPart: "Triceps",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Single Leg Seated Calf Raise",
    slug: "single-leg-seated-calf-raise",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Standing Leg Curl",
    slug: "standing-leg-curl",
    bodyPart: "Legs",
    type: "machine",
    category: "Machine",
    aliases: [],
  },
  {
    name: "Lat Pulldown",
    slug: "lat-pulldown",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: ["Machine Pulldown", "Back Lat Pulldown", "Lateral Pulldown"],
  },
  {
    name: "Tricep Pushdown",
    slug: "tricep-pushdown",
    bodyPart: "Triceps",
    type: "cable",
    category: "Cable",
    aliases: ["Tricep Pressdown", "Cable Tricep Extension"],
  },
  {
    name: "Seated Cable Row",
    slug: "seated-cable-row",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: ["Seated Row", "Low Row"],
  },
  {
    name: "Face Pull",
    slug: "face-pull",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Tricep Rope Pushdown",
    slug: "tricep-rope-pushdown",
    bodyPart: "Triceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Bicep Curl",
    slug: "cable-bicep-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: ["Cable Curl", "Biceps Cable Curl", "Standing Cable Curl"],
  },
  {
    name: "Cable Crossover",
    slug: "cable-crossover",
    bodyPart: "Chest",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Fly",
    slug: "cable-fly",
    bodyPart: "Chest",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Straight Arm Pulldown",
    slug: "straight-arm-pulldown",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: ["Straight Arm Lat Pulldown"],
  },
  {
    name: "Cable Shrug",
    slug: "cable-shrug",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Reverse Grip Lat Pulldown",
    slug: "reverse-grip-lat-pulldown",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: ["Reverse Grip Pulldown", "Palm Up Pulldown"],
  },
  {
    name: "Cable Overhead Tricep Extension",
    slug: "cable-overhead-tricep-extension",
    bodyPart: "Triceps",
    type: "cable",
    category: "Cable",
    aliases: [
      "Overhead Tricep Rope Extension",
      "Overhead Tricep Cable Extension",
      "Overhead Cable Tricep Extension",
      "Tricep Overhead Extension",
    ],
  },
  {
    name: "Cable Lateral Raise",
    slug: "cable-lateral-raise",
    bodyPart: "Shoulders",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "One Arm Seated Cable Row",
    slug: "one-arm-seated-cable-row",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "One Arm Cable Bicep Curl",
    slug: "one-arm-cable-bicep-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: ["One Arm Cable Curl"],
  },
  {
    name: "Cable Crunch",
    slug: "cable-crunch",
    bodyPart: "Core",
    type: "cable",
    category: "Cable",
    aliases: ["Cable Crunches"],
  },
  {
    name: "Cable Leg Extension",
    slug: "cable-leg-extension",
    bodyPart: "Legs",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Reverse Fly",
    slug: "cable-reverse-fly",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Woodchoppers",
    slug: "cable-woodchoppers",
    bodyPart: "Core",
    type: "cable",
    category: "Cable",
    aliases: ["Wood Chopper", "Cable Wood Chop"],
  },
  {
    name: "Cable Hammer Curl",
    slug: "cable-hammer-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Behind The Back Cable Curl",
    slug: "behind-the-back-cable-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Kickback",
    slug: "cable-kickback",
    bodyPart: "Legs",
    type: "cable",
    category: "Cable",
    aliases: ["Cable Standing Glute Kickback", "Cable Tricep Kickback"],
  },
  {
    name: "One Arm Lat Pulldown",
    slug: "one-arm-lat-pulldown",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Upright Row",
    slug: "cable-upright-row",
    bodyPart: "Back",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable External Rotation",
    slug: "cable-external-rotation",
    bodyPart: "Shoulders",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Standing Cable Crunch",
    slug: "standing-cable-crunch",
    bodyPart: "Core",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Overhead Cable Curl",
    slug: "overhead-cable-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "One Arm Pulldown",
    slug: "one-arm-pulldown",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Lying Cable Curl",
    slug: "lying-cable-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Incline Cable Curl",
    slug: "incline-cable-curl",
    bodyPart: "Biceps",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Reverse Grip Tricep Pushdown",
    slug: "reverse-grip-tricep-pushdown",
    bodyPart: "Triceps",
    type: "cable",
    category: "Cable",
    aliases: ["Reverse Grip Tricep Extension"],
  },
  {
    name: "High Pulley Crunch",
    slug: "high-pulley-crunch",
    bodyPart: "Core",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
  {
    name: "Cable Pull Through",
    slug: "cable-pull-through",
    bodyPart: "Legs",
    type: "cable",
    category: "Cable",
    aliases: [],
  },
];
